import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconFolder,
  IconUsers,
  IconCrown,
  IconStar,
  IconBox,
  IconPalette,
  IconBuilding,
  IconShip,
  IconCalculator,
  IconClipboardList,
  IconReportMoney
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconBox,
  palette: IconPalette,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  user: IconUser,
  users: IconUsers,
  userCircle: IconUserCircle,
  userEdit: IconUserEdit,
  userX: IconUserX,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  star: IconStar,
  laptop: IconDeviceLaptop,
  gitHub: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  // Detailed mapping for nav-config
  workspace: IconFolder,
  teams: IconUsers,
  pro: IconCrown,
  exclusive: IconStar,
  account: IconUserCircle,
  profile: IconUser,
  billing: IconCreditCard,
  // CRM icons
  crm: IconLayoutDashboard,
  leads: IconPhoto,
  deals: IconShoppingBag,
  contacts: IconUsers,
  activities: IconFile,
  emails: IconFileText,
  crmSettings: IconSettings,
  building: IconBuilding,
  // Underwriting icons
  underwriting: IconShip,
  submissions: IconClipboardList,
  calculator: IconCalculator,
  quotes: IconReportMoney
};
